apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: voyager
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/nix80csh/voyager-infra.git
  destinations:
    - namespace: 'karpenter'
      server: https://4DE867698BF1D9F5099CF5329BF0DAF4.gr7.ap-northeast-2.eks.amazonaws.com
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
