apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: karpenter-read-configmaps
  namespace: karpenter
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: karpenter-read-configmaps-binding
  namespace: karpenter
subjects:
- kind: ServiceAccount
  name: karpenter
  namespace: karpenter
roleRef:
  kind: Role
  name: karpenter-read-configmaps
  apiGroup: rbac.authorization.k8s.io
