apiVersion: karpenter.sh/v1
kind: Provisioner
metadata:
  name: ondemand
spec:
  requirements:
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t3.large"]
  provider:
    instanceProfile: karpenter-node-instance-profile
  ttlSecondsAfterEmpty: 30
  consolidation:
    enabled: true
  weight: 10